from pathlib import Path
import json
import msgpack  # pip install msgpack

star_hub_path = Path("the_funny_1.json")
zeke_hub_path = Path("the_funny_2.json")
mp_path   = Path("Timings/Juanito/mainjuan_fixed_imported.txt")

def load_json(p: Path):
    if not p.exists() or p.stat().st_size == 0:
        return {}
    return json.loads(p.read_text(encoding="utf-8"))

def load_msgpack(p: Path):
    if not p.exists() or p.stat().st_size == 0:
        return {}
    return msgpack.unpackb(p.read_bytes(), raw=False)

star_hub_json = load_json(star_hub_path)
zeke_hub_json = load_json(zeke_hub_path)
current   = load_msgpack(mp_path)

anim_table_1 = current.get("animation")
anim_table_2 = star_hub_json
anim_table_3 = zeke_hub_json

def find_timing_from_timing_id(timing_id):
    for at in anim_table_1: # type: ignore
        if at.get("_id") == timing_id:
            return at

    return None

for key, timing in anim_table_2.items():
    if find_timing_from_timing_id(key):
        continue

    print(f"(Star Hub Beta) Generating missing timing found for {key}: {timing.get("Name")}")
 
    # [anim_table_1]
    # {
        # 'rsd': 0, 
        # 'umoa': False, 
        # 'rpd': 0, 
        # 'smod': 'N/A', 
        # 'ieae': False, '
        # scrambled': False, 
        # 'iae': False, 
        # 'actions': [{'_type': 'Parry', 'name': '1', 'hitbox': {'Y': 0, 'X': 0, 'Z': 0}, 'when': 0, 'ihbc': False}], 
        # 'ha': False, 
        # 'ndfb': False, 'duih': True, 'after': 0, 
        # '_id': 'rbxassetid://14071038319', 'mat': 0, 'rpue': False,
        # 'srpn': False, 'aatk': False, 
        # 'hitbox': {'Y': 15, 'X': 15, 'Z': 29}, 'punishable': 0, 'name': 'ByakoGo', 
        # 'imxd': 107, 'smn': False, 'fhb': True, 'imdd': 10, '
        # tag': 'Undefined'
    # }
    
    # [anim_table_2]
    #  "RepeatParryDelay": 50,
    #  "Name": "SchwertM1_3",
    #  "RepeatParryAmount": 0,
    #  "Roll": false,
    #  "Range": 11,
    #  "Wait": 280
    actions = [{
        '_type': timing.get("Roll") == True and "Dash" or 'Parry',
        'name': '1',
        'hitbox': {'Y': timing.get("Range"), 'X': timing.get("Range"), 'Z': timing.get("Range")},
        'when': timing.get("Wait"),
        'ihbc': False
    }]

    anim_table_1.append({ # type: ignore
        "rsd": 0,
        "umoa": False,
        "rpd": 0,
        'smod': "N/A",
        'ha': False,
        'ndfb': False,
        'duih': False,
        'after': 0,
        '_id': key,
        'mat': 0,
        'rpue': False,
        'srpn': False,
        'aatk': False,
        'actions': actions,
        'hitbox': {'Y': 0, 'X': 0, 'Z': 0},
        'punishable': 0,
        'name': timing.get("Name"),
        'imxd': timing.get("Range") + 50,
        'smn': False,
        'fhb': False,
        'imdd': 0,
        'tag': 'Undefined'
    })


for key, timing in anim_table_3.items():
    try:
        int(key)
    except ValueError:
        print(f"(Zeke Hub) Skipping key {key} because it is not an animation")
        continue

    timing = find_timing_from_timing_id("rbxassetid://" + key)

    if not timing:
        continue

    if timing.smod.endswith(".lua"):
        timing.smod = timing.smod[:-4]

    print(f"(Zeke Hub) Fixed 'smod' for rbxassetid://{key}")

for key, timing in anim_table_3.items():
    try:
        int(key)
    except ValueError:
        print(f"(Zeke Hub) Skipping key {key} because it is not an animation")
        continue

    if find_timing_from_timing_id("rbxassetid://" + key):
        continue

    print(f"(Zeke Hub) No matching timing found for rbxassetid://{key}")

    anim_table_1.append({ # type: ignore
        "rsd": 0,
        "umoa": True,
        "rpd": 0,
        'smod': "HF_" + key + "_AutoGenerated",
        'ha': False,
        'ndfb': False,
        'duih': False,
        'after': 0,
        '_id': "rbxassetid://" + key,
        'mat': 0,
        'rpue': False,
        'srpn': False,
        'aatk': False,
        'actions': [],
        'hitbox': {'Y': 0, 'X': 0, 'Z': 0},
        'punishable': 0,
        'name': "HF_" + key + "_AutoGenerated",
        'imxd': 50,
        'smn': False,
        'fhb': False,
        'imdd': 0,
        'tag': 'Undefined'
    })
    
    first_hit_time = timing.get("hitFrameTimes")[0]
    builder_string = (
        "---@type Action\n"
        "local Action = getfenv().Action\n\n"
        "---Module function.\n"
        "---@param self AnimatorDefender\n"
        "---@param timing AnimationTiming\n"
        "return function(self, timing)\n"
        "    local action = Action.new()\n"
        "    action._type = \"Parry\"\n"
        "    action.hitbox = Vector3.new(30, 30, 30)\n"
        "    action.name = \"Keyframe Action\"\n"
        f"    return self:akeyframe(action, {first_hit_time})\n"
        "end"
    )

    modules_path = Path("Modules")
    modules_path.mkdir(exist_ok=True)

    module_file = modules_path / f"HF_{key}_AutoGenerated.lua"
    if not module_file.exists():
        module_file.write_text(builder_string, encoding="utf-8")
        print(f"Created module file: {module_file}")
    else:
        print(f"Module file already exists: {module_file}")

# Write out new messagepack with _imported suffix
fixed_path = mp_path if mp_path.name.endswith("_imported.txt") else mp_path.with_name(mp_path.stem + "_imported" + mp_path.suffix)

try:
    packed = msgpack.packb(current, use_bin_type=True)  # type: ignore[assignment]
    fixed_path.write_bytes(packed)  # type: ignore[arg-type]
    print(f"Wrote fixed timings to {fixed_path}")
except Exception as e:
    print(f"Error writing fixed timings: {e}")